language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -U pip
  - pip install -U .
  - pip install -U ".[test]"
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=picas tests
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6* ]]; then flake8 picas; fi
